### ISSUE TITLE
When redirected to PayPal website via link at top, return to app and Back button is not respected

### ISSUE THREAD

**Issue by jforaker** [surialabs/react-native-braintree-android#4]
If you click on the Paypal button on top, you are redirected to the Paypal website in the browser.

Press the back button you will return the app. 

**NOW** if you press the back button again, it will not fire a `BackAndroid hardwareBackPress` event. Nothing happens and you are _stuck_ in the payment screen. At this point you have to kill the app to get out of the payment screen. 

p.s. thank you for the great plugin :+1:

**Comment by lkorth** [comment]
This was an issue with `braintree_android` and fixed in 2.2.0
